# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.1.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.1.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/agata/Desktop/CodingProjects/SampleLibSVM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/agata/Desktop/CodingProjects/SampleLibSVM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/Cellar/cmake/3.1.1/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.1.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/agata/Desktop/CodingProjects/SampleLibSVM/CMakeFiles /Users/agata/Desktop/CodingProjects/SampleLibSVM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/agata/Desktop/CodingProjects/SampleLibSVM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SampleLibSVM

# Build rule for target.
SampleLibSVM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SampleLibSVM
.PHONY : SampleLibSVM

# fast build rule for target.
SampleLibSVM/fast:
	$(MAKE) -f CMakeFiles/SampleLibSVM.dir/build.make CMakeFiles/SampleLibSVM.dir/build
.PHONY : SampleLibSVM/fast

#=============================================================================
# Target rules for targets named libsvm_lib

# Build rule for target.
libsvm_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libsvm_lib
.PHONY : libsvm_lib

# fast build rule for target.
libsvm_lib/fast:
	$(MAKE) -f CMakeFiles/libsvm_lib.dir/build.make CMakeFiles/libsvm_lib.dir/build
.PHONY : libsvm_lib/fast

src/SampleLibSVM.o: src/SampleLibSVM.cpp.o
.PHONY : src/SampleLibSVM.o

# target to build an object file
src/SampleLibSVM.cpp.o:
	$(MAKE) -f CMakeFiles/SampleLibSVM.dir/build.make CMakeFiles/SampleLibSVM.dir/src/SampleLibSVM.cpp.o
.PHONY : src/SampleLibSVM.cpp.o

src/SampleLibSVM.i: src/SampleLibSVM.cpp.i
.PHONY : src/SampleLibSVM.i

# target to preprocess a source file
src/SampleLibSVM.cpp.i:
	$(MAKE) -f CMakeFiles/SampleLibSVM.dir/build.make CMakeFiles/SampleLibSVM.dir/src/SampleLibSVM.cpp.i
.PHONY : src/SampleLibSVM.cpp.i

src/SampleLibSVM.s: src/SampleLibSVM.cpp.s
.PHONY : src/SampleLibSVM.s

# target to generate assembly for a file
src/SampleLibSVM.cpp.s:
	$(MAKE) -f CMakeFiles/SampleLibSVM.dir/build.make CMakeFiles/SampleLibSVM.dir/src/SampleLibSVM.cpp.s
.PHONY : src/SampleLibSVM.cpp.s

src/libsvm-3.20/svm-predict.o: src/libsvm-3.20/svm-predict.c.o
.PHONY : src/libsvm-3.20/svm-predict.o

# target to build an object file
src/libsvm-3.20/svm-predict.c.o:
	$(MAKE) -f CMakeFiles/libsvm_lib.dir/build.make CMakeFiles/libsvm_lib.dir/src/libsvm-3.20/svm-predict.c.o
.PHONY : src/libsvm-3.20/svm-predict.c.o

src/libsvm-3.20/svm-predict.i: src/libsvm-3.20/svm-predict.c.i
.PHONY : src/libsvm-3.20/svm-predict.i

# target to preprocess a source file
src/libsvm-3.20/svm-predict.c.i:
	$(MAKE) -f CMakeFiles/libsvm_lib.dir/build.make CMakeFiles/libsvm_lib.dir/src/libsvm-3.20/svm-predict.c.i
.PHONY : src/libsvm-3.20/svm-predict.c.i

src/libsvm-3.20/svm-predict.s: src/libsvm-3.20/svm-predict.c.s
.PHONY : src/libsvm-3.20/svm-predict.s

# target to generate assembly for a file
src/libsvm-3.20/svm-predict.c.s:
	$(MAKE) -f CMakeFiles/libsvm_lib.dir/build.make CMakeFiles/libsvm_lib.dir/src/libsvm-3.20/svm-predict.c.s
.PHONY : src/libsvm-3.20/svm-predict.c.s

src/libsvm-3.20/svm-scale.o: src/libsvm-3.20/svm-scale.c.o
.PHONY : src/libsvm-3.20/svm-scale.o

# target to build an object file
src/libsvm-3.20/svm-scale.c.o:
	$(MAKE) -f CMakeFiles/libsvm_lib.dir/build.make CMakeFiles/libsvm_lib.dir/src/libsvm-3.20/svm-scale.c.o
.PHONY : src/libsvm-3.20/svm-scale.c.o

src/libsvm-3.20/svm-scale.i: src/libsvm-3.20/svm-scale.c.i
.PHONY : src/libsvm-3.20/svm-scale.i

# target to preprocess a source file
src/libsvm-3.20/svm-scale.c.i:
	$(MAKE) -f CMakeFiles/libsvm_lib.dir/build.make CMakeFiles/libsvm_lib.dir/src/libsvm-3.20/svm-scale.c.i
.PHONY : src/libsvm-3.20/svm-scale.c.i

src/libsvm-3.20/svm-scale.s: src/libsvm-3.20/svm-scale.c.s
.PHONY : src/libsvm-3.20/svm-scale.s

# target to generate assembly for a file
src/libsvm-3.20/svm-scale.c.s:
	$(MAKE) -f CMakeFiles/libsvm_lib.dir/build.make CMakeFiles/libsvm_lib.dir/src/libsvm-3.20/svm-scale.c.s
.PHONY : src/libsvm-3.20/svm-scale.c.s

src/libsvm-3.20/svm-train.o: src/libsvm-3.20/svm-train.c.o
.PHONY : src/libsvm-3.20/svm-train.o

# target to build an object file
src/libsvm-3.20/svm-train.c.o:
	$(MAKE) -f CMakeFiles/libsvm_lib.dir/build.make CMakeFiles/libsvm_lib.dir/src/libsvm-3.20/svm-train.c.o
.PHONY : src/libsvm-3.20/svm-train.c.o

src/libsvm-3.20/svm-train.i: src/libsvm-3.20/svm-train.c.i
.PHONY : src/libsvm-3.20/svm-train.i

# target to preprocess a source file
src/libsvm-3.20/svm-train.c.i:
	$(MAKE) -f CMakeFiles/libsvm_lib.dir/build.make CMakeFiles/libsvm_lib.dir/src/libsvm-3.20/svm-train.c.i
.PHONY : src/libsvm-3.20/svm-train.c.i

src/libsvm-3.20/svm-train.s: src/libsvm-3.20/svm-train.c.s
.PHONY : src/libsvm-3.20/svm-train.s

# target to generate assembly for a file
src/libsvm-3.20/svm-train.c.s:
	$(MAKE) -f CMakeFiles/libsvm_lib.dir/build.make CMakeFiles/libsvm_lib.dir/src/libsvm-3.20/svm-train.c.s
.PHONY : src/libsvm-3.20/svm-train.c.s

src/libsvm-3.20/svm.o: src/libsvm-3.20/svm.cpp.o
.PHONY : src/libsvm-3.20/svm.o

# target to build an object file
src/libsvm-3.20/svm.cpp.o:
	$(MAKE) -f CMakeFiles/libsvm_lib.dir/build.make CMakeFiles/libsvm_lib.dir/src/libsvm-3.20/svm.cpp.o
.PHONY : src/libsvm-3.20/svm.cpp.o

src/libsvm-3.20/svm.i: src/libsvm-3.20/svm.cpp.i
.PHONY : src/libsvm-3.20/svm.i

# target to preprocess a source file
src/libsvm-3.20/svm.cpp.i:
	$(MAKE) -f CMakeFiles/libsvm_lib.dir/build.make CMakeFiles/libsvm_lib.dir/src/libsvm-3.20/svm.cpp.i
.PHONY : src/libsvm-3.20/svm.cpp.i

src/libsvm-3.20/svm.s: src/libsvm-3.20/svm.cpp.s
.PHONY : src/libsvm-3.20/svm.s

# target to generate assembly for a file
src/libsvm-3.20/svm.cpp.s:
	$(MAKE) -f CMakeFiles/libsvm_lib.dir/build.make CMakeFiles/libsvm_lib.dir/src/libsvm-3.20/svm.cpp.s
.PHONY : src/libsvm-3.20/svm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SampleLibSVM"
	@echo "... libsvm_lib"
	@echo "... src/SampleLibSVM.o"
	@echo "... src/SampleLibSVM.i"
	@echo "... src/SampleLibSVM.s"
	@echo "... src/libsvm-3.20/svm-predict.o"
	@echo "... src/libsvm-3.20/svm-predict.i"
	@echo "... src/libsvm-3.20/svm-predict.s"
	@echo "... src/libsvm-3.20/svm-scale.o"
	@echo "... src/libsvm-3.20/svm-scale.i"
	@echo "... src/libsvm-3.20/svm-scale.s"
	@echo "... src/libsvm-3.20/svm-train.o"
	@echo "... src/libsvm-3.20/svm-train.i"
	@echo "... src/libsvm-3.20/svm-train.s"
	@echo "... src/libsvm-3.20/svm.o"
	@echo "... src/libsvm-3.20/svm.i"
	@echo "... src/libsvm-3.20/svm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

